/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gymsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sid
 */
public class Admin_login extends javax.swing.JFrame {
Connection con = null;
    ResultSet rs = null;
     PreparedStatement pst = null;
    /**
     * Creates new form Admin_login
     */
    public Admin_login() {
        initComponents();
        con = postgres.conectDB();
        getContentPane().setBackground(new Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        adminID = new javax.swing.JTextField();
        s_user = new javax.swing.JButton();
        login = new javax.swing.JButton();
        Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 80, 100, 22);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel2.setText("AdminID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 80, 22);

        adminID.setToolTipText("");
        jPanel1.add(adminID);
        adminID.setBounds(130, 30, 140, 28);

        s_user.setBackground(new java.awt.Color(255, 255, 102));
        s_user.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        s_user.setForeground(new java.awt.Color(89, 42, 138));
        s_user.setText("Switch User");
        s_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_userActionPerformed(evt);
            }
        });
        jPanel1.add(s_user);
        s_user.setBounds(100, 140, 140, 30);

        login.setBackground(new java.awt.Color(255, 255, 102));
        login.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(89, 42, 138));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(10, 140, 95, 30);
        jPanel1.add(Password);
        Password.setBounds(130, 90, 140, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gymsystem/East_Carolina_Pirates_cover.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_userActionPerformed
         UserInfo UI = new UserInfo();
        UI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_s_userActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       
        
        
         String sql = "select * from Admin_info where adminid = ? and password = ?";
        try{
            
            con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/project", "postgres","sid3791");
            pst=con.prepareStatement(sql);
            pst.setString(1, adminID.getText());
           
               String value =  adminID.getText();
            pst.setString(2, Password.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "AdminID and Password are Correct");
                rs.close();
                pst.close();
                Admin_MP AMP = new Admin_MP();
                AMP.setVisible(true);
                this.setVisible(false);
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "AdminID and Password are InCorrect");
        }
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField adminID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JButton s_user;
    // End of variables declaration//GEN-END:variables
}
