/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gymsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
public class Login_jframe extends javax.swing.JFrame {
    Connection con = null;
    ResultSet rs = null;
     PreparedStatement pst = null;
    /**
     * Creates new form Login_jframe
     */
    public Login_jframe() {
        initComponents();
        con = postgres.conectDB();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        s_user = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PirateID = new javax.swing.JTextField();
        Password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(null);

        s_user.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        s_user.setText("Switch User");
        s_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s_userActionPerformed(evt);
            }
        });
        jPanel1.add(s_user);
        s_user.setBounds(330, 120, 130, 30);

        jLabel1.setBackground(new java.awt.Color(89, 42, 138));
        jLabel1.setText("PirateID");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 49, 16);

        jLabel2.setBackground(new java.awt.Color(89, 42, 138));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 50, 59, 16);

        PirateID.setToolTipText("");
        jPanel1.add(PirateID);
        PirateID.setBounds(440, 0, 94, 28);
        jPanel1.add(Password);
        Password.setBounds(440, 40, 94, 28);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 90, 100, 29);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jButton2.setText("Login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 90, 120, 29);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel3.setText("New Member");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(460, 120, 110, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gymsystem/ecu-pirates-logo-jpg.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-10, -10, 580, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String sql = "select * from user_info where pirateid=? and password=?";
        try{
            
            con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/project", "postgres","sid3791");
            pst=con.prepareStatement(sql);
            pst.setString(1, PirateID.getText());
           
               String value =  PirateID.getText();
            pst.setString(2, Password.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "PirateID and password are Correct");
                rs.close();
                pst.close();
                Main_page MP = new Main_page();
                MP.setVisible(true);
                MP.pack();
                this.setVisible(false);
                // B1 = new BMI(Username.toString());
                //B1.show();
            }
            else{
                JOptionPane.showMessageDialog(null, "PirateID and Password Incorrect");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Register R1 = new Register();
            R1.setVisible(true);
            
            this.setVisible(false);
             
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void s_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s_userActionPerformed
        
        
        UserInfo UI = new UserInfo();
        UI.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_s_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField PirateID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton s_user;
    // End of variables declaration//GEN-END:variables
}
