/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gymsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sid
 */
public class Supplement extends javax.swing.JFrame {

    /**
     * Creates new form Supplement
     */ 
    private String sup;
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;  
     DefaultTableModel model;
     
     public void groupButton(){
         
         Supplement.add(bcca);
         Supplement.add(Whey_protein);
         Supplement.add(Casein_protein);
         Supplement.add(multi_vitamin);
         Supplement.add(weight_loss);
         Supplement.add(pre_workout);
     }
    public Supplement() {
        initComponents();
        this.con = postgres.conectDB();
         model = (DefaultTableModel) Supp_table.getModel();
    }

    private void update_table() {
        try
        {
            this.con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/project", "postgres","sid3791");
        String sql ="select supplement,serving_size ServingSize, cost_$ Dollars from Supplement where supplement_name ='"+sup+"'"; 
         pst=con.prepareStatement(sql);
       
        rs= pst.executeQuery();
        Supp_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Supplement = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        Supp_table = new javax.swing.JTable();
        Whey_protein = new javax.swing.JRadioButton();
        Casein_protein = new javax.swing.JRadioButton();
        pre_workout = new javax.swing.JRadioButton();
        weight_loss = new javax.swing.JRadioButton();
        multi_vitamin = new javax.swing.JRadioButton();
        bcca = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Supp_table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        Supp_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Supp_table.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(Supp_table);

        Whey_protein.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Whey_protein.setText("Whey Protein ");
        Whey_protein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Whey_proteinActionPerformed(evt);
            }
        });

        Casein_protein.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        Casein_protein.setText("Casein Protein");
        Casein_protein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Casein_proteinActionPerformed(evt);
            }
        });

        pre_workout.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        pre_workout.setText("Pre-Workout");
        pre_workout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pre_workoutActionPerformed(evt);
            }
        });

        weight_loss.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        weight_loss.setText("Weight Loss");
        weight_loss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight_lossActionPerformed(evt);
            }
        });

        multi_vitamin.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        multi_vitamin.setText("Multi-Vitamin");
        multi_vitamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multi_vitaminActionPerformed(evt);
            }
        });

        bcca.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        bcca.setText("BCCA");
        bcca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bccaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(89, 42, 138));
        jButton1.setText("Search ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(89, 42, 138));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gymsystem/Logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 455, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pre_workout)
                        .addGap(89, 89, 89)
                        .addComponent(bcca))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Whey_protein)
                            .addComponent(Casein_protein))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(multi_vitamin)
                            .addComponent(weight_loss)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Whey_protein)
                    .addComponent(weight_loss))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Casein_protein)
                    .addComponent(multi_vitamin))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pre_workout)
                    .addComponent(bcca))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Casein_proteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Casein_proteinActionPerformed
        sup ="Casein Protein";
        Supplement.add(Casein_protein);
        this.add(Casein_protein);
        Casein_protein.setVisible(true);
    }//GEN-LAST:event_Casein_proteinActionPerformed

    private void Whey_proteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Whey_proteinActionPerformed
        sup ="Whey Protein";
        Supplement.add(Whey_protein);
        this.add(Whey_protein);
        Whey_protein.setVisible(true);
        
    }//GEN-LAST:event_Whey_proteinActionPerformed

    private void pre_workoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pre_workoutActionPerformed
        sup ="Pre-Workout";
        Supplement.add(pre_workout);
        this.add(pre_workout);
        pre_workout.setVisible(true);
    }//GEN-LAST:event_pre_workoutActionPerformed

    private void weight_lossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight_lossActionPerformed
        
        sup ="Fat Burner";
        Supplement.add(weight_loss);
        this.add(weight_loss);
        weight_loss.setVisible(true);
    }//GEN-LAST:event_weight_lossActionPerformed

    private void multi_vitaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multi_vitaminActionPerformed
       sup ="Multi-Vitamin";
       Supplement.add(multi_vitamin);
       this.add(multi_vitamin);
       multi_vitamin.setVisible(true);
        
    }//GEN-LAST:event_multi_vitaminActionPerformed

    private void bccaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bccaActionPerformed
        
        sup ="BCCA";
        Supplement.add(bcca);
        this.add(bcca);
        bcca.setVisible(true);
    }//GEN-LAST:event_bccaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        update_table();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Main_page MP = new Main_page();
        MP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Casein_protein;
    private javax.swing.JTable Supp_table;
    private javax.swing.ButtonGroup Supplement;
    private javax.swing.JRadioButton Whey_protein;
    private javax.swing.JRadioButton bcca;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton multi_vitamin;
    private javax.swing.JRadioButton pre_workout;
    private javax.swing.JRadioButton weight_loss;
    // End of variables declaration//GEN-END:variables

    
}
