/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gymsystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author sid
 */
public class Workout extends javax.swing.JFrame {
    
    private  String body_part;
    private String work_level;
    private String work_type;
    String body = new String();
        String level= new String();
        String type = new String();
        Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;  
    DefaultTableModel model;
    /**
     * 
     * 
     * Creates new form Dietitian
     */
    
    public void groupButton()
    {
        Workout_type.add(Muscle_Building);
        Workout_type.add(Endurance);
        Bodypart.add(Chest);
        Bodypart.add(Shoulder);
        Bodypart.add(Arms);
        Bodypart.add(Legs);
       ;
    }
    public void onSumbit()
    {
        if(Chest.isSelected())
            body="Chest";
        
        if(Shoulder.isSelected())
            body = "Shoulder";
        if(Arms.isSelected())
            body = "Arm";
        if(Legs.isSelected())
            body ="Legs";
        
        
    }
    public Workout() {
        initComponents();
        this.con = postgres.conectDB();
         model = (DefaultTableModel) Wod_table.getModel();
        //update_table();
         getContentPane().setBackground(new Color(255,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bodypart = new javax.swing.ButtonGroup();
        Workout_Level = new javax.swing.ButtonGroup();
        Workout_type = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Chest = new javax.swing.JRadioButton();
        Shoulder = new javax.swing.JRadioButton();
        Arms = new javax.swing.JRadioButton();
        Legs = new javax.swing.JRadioButton();
        Beginner = new javax.swing.JRadioButton();
        Intermediate = new javax.swing.JRadioButton();
        Advance = new javax.swing.JRadioButton();
        Muscle_Building = new javax.swing.JRadioButton();
        Endurance = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Wod_table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Email = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel1.setText("Bodypart");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel2.setText("Level");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel3.setText("Type");
        jLabel3.setToolTipText("");

        Chest.setText("Chest");
        Chest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChestActionPerformed(evt);
            }
        });

        Shoulder.setText("Shoulder");
        Shoulder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShoulderActionPerformed(evt);
            }
        });

        Arms.setText("Arms");
        Arms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArmsActionPerformed(evt);
            }
        });

        Legs.setText("Legs");
        Legs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LegsActionPerformed(evt);
            }
        });

        Beginner.setText("Beginner");
        Beginner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeginnerActionPerformed(evt);
            }
        });

        Intermediate.setText("Intermediate ");
        Intermediate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntermediateActionPerformed(evt);
            }
        });

        Advance.setText("Advance");
        Advance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdvanceActionPerformed(evt);
            }
        });

        Muscle_Building.setText("Muscle Building");
        Muscle_Building.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Muscle_BuildingActionPerformed(evt);
            }
        });

        Endurance.setText("Endurance");
        Endurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnduranceActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 199, 2));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(89, 42, 138));
        jButton1.setText("WOD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Wod_table.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0), null, new java.awt.Color(0, 0, 0)));
        Wod_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Wod_table.setGridColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(Wod_table);

        jButton5.setBackground(new java.awt.Color(255, 199, 2));
        jButton5.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(89, 42, 138));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 199, 2));
        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(89, 42, 138));
        jButton3.setText("Send Email");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gymsystem/Peedee.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gymsystem/UNDAUNTED.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Chest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(Intermediate))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Arms))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(Muscle_Building))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Beginner))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Legs))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(Endurance))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(Advance))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Shoulder))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Chest)
                        .addGap(6, 6, 6)
                        .addComponent(Intermediate)
                        .addGap(6, 6, 6)
                        .addComponent(Arms))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(Beginner))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(Legs))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(Advance))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(Shoulder)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton5))
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Muscle_Building))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(Endurance)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(33, 33, 33)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ArmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArmsActionPerformed
    body_part = "Arms";
    Bodypart.add(Chest);
        Bodypart.add(Shoulder);
        Bodypart.add(Arms);
        Bodypart.add(Legs);
        this.add(Shoulder);
        this.add(Arms);
        this.add(Legs);
        this.add(Chest);
        Arms.setSelected(true);
    }//GEN-LAST:event_ArmsActionPerformed

    private void EnduranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnduranceActionPerformed
        work_type = "Endurance";
        Workout_type.add(Muscle_Building);
        Workout_type.add(Endurance);
        this.add(Muscle_Building);
        this.add(Endurance);
        Endurance.setSelected(true);        // TODO add your handling code here:
    }//GEN-LAST:event_EnduranceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
update_table();
       //WOD wod = new WOD();
      // wod.setVisible(true);
      // this.setVisible(false);
       
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ChestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChestActionPerformed

        body_part = "Chest";
        
        Bodypart.add(Chest);
        Bodypart.add(Shoulder);
        Bodypart.add(Arms);
        Bodypart.add(Legs);
        this.add(Shoulder);
        this.add(Arms);
        this.add(Legs);
        this.add(Chest);
        Chest.setSelected(true);
       
    }//GEN-LAST:event_ChestActionPerformed
private void update_table() {
        try
        {
            this.con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/project", "postgres","sid3791");
        String sql ="select w_name,bodypart,no_set from workout where bodypart='"+body_part+"'and w_level = '"+work_level+"'order by random() limit 5"; 
         pst=con.prepareStatement(sql);
       
        rs= pst.executeQuery();
        
        Wod_table.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        }
    private void Muscle_BuildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Muscle_BuildingActionPerformed
        work_type = "Muscle Building";
        Workout_type.add(Muscle_Building);
        Workout_type.add(Endurance);
        this.add(Muscle_Building);
        this.add(Endurance);
        Muscle_Building.setSelected(true);
        
       
        
    }//GEN-LAST:event_Muscle_BuildingActionPerformed

    private void BeginnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeginnerActionPerformed
        work_level="Beginner";
        Workout_Level.add(Beginner);
       Workout_Level.add(Intermediate);
       Workout_Level.add(Advance);
       this.add(Beginner);
       this.add(Intermediate);
       this.add(Advance);
       Beginner.setSelected(true);
    }//GEN-LAST:event_BeginnerActionPerformed

    private void ShoulderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShoulderActionPerformed
        body_part = "Shoulder";
        Bodypart.add(Chest);
        Bodypart.add(Shoulder);
        Bodypart.add(Arms);
        Bodypart.add(Legs);
        this.add(Shoulder);
        this.add(Arms);
        this.add(Legs);
        this.add(Chest);
        Shoulder.setSelected(true);
    }//GEN-LAST:event_ShoulderActionPerformed

    private void LegsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LegsActionPerformed
        body_part = "Legs";
        Bodypart.add(Chest);
        Bodypart.add(Shoulder);
        Bodypart.add(Arms);
        Bodypart.add(Legs);
        this.add(Shoulder);
        this.add(Arms);
        this.add(Legs);
        this.add(Chest);
        Legs.setSelected(true);
    }//GEN-LAST:event_LegsActionPerformed

    private void IntermediateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntermediateActionPerformed
        work_level="Intermediate";
         Workout_Level.add(Beginner);
       Workout_Level.add(Intermediate);
       Workout_Level.add(Advance);
       this.add(Beginner);
       this.add(Intermediate);
       this.add(Advance);
       Intermediate.setSelected(true);
    }//GEN-LAST:event_IntermediateActionPerformed

    private void AdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdvanceActionPerformed
        work_level="Advance";
         Workout_Level.add(Beginner);
       Workout_Level.add(Intermediate);
       Workout_Level.add(Advance);
       this.add(Beginner);
       this.add(Intermediate);
       this.add(Advance);
       Advance.setSelected(true);
    }//GEN-LAST:event_AdvanceActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Main_page mp1 = new Main_page();
        mp1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        Properties props = new Properties();
        
        props.put("mail.smtp.host", "imap.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth" ,"true");
        props.put("mail.smtp.port","465");
        
        Session session;
        session = Session.getInstance(props,new javax.mail.Authenticator() {
            
            protected PasswordAuthentication getPasswordAuthentication()
            {
                return new PasswordAuthentication("ecugym@gmail.com", "ECU12345");
                        }
        });
        try{
           
           // PreparedStatement pst = null;
          // con=DriverManager.getConnection("jdbc:postgresql://localhost:5432/project", "postgres","sid3791");
          // String sql ="select e_mail from user_info where username='patelsi14';";
            //pst = con.prepareStatement(sql);
            
            
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("ecugym@gmail.com"));
            message.setRecipients(Message.RecipientType.TO,InternetAddress.parse(Email.getText()));
            message.setSubject("WOD");
            message.setText("WOD Consists of following details:"+"\n"+"Body Part:"+body_part+"\n"+"Workout Level:"+work_level+"\n"+"Workout Type:"+work_type
                    +"\n\n"+"(1)"+Wod_table.getModel().getValueAt(0, 0).toString()+":"+Wod_table.getModel().getValueAt(0, 2).toString()
                    +"\n"+"(2)"+Wod_table.getModel().getValueAt(1, 0).toString()+":"+Wod_table.getModel().getValueAt(1, 2).toString()
                    +"\n"+"(3)"+Wod_table.getModel().getValueAt(2, 0).toString()+":"+Wod_table.getModel().getValueAt(2, 2).toString()
                    +"\n"+"(4)"+Wod_table.getModel().getValueAt(3, 0).toString()+":"+Wod_table.getModel().getValueAt(3, 2).toString()
                    +"\n"+"(5)"+Wod_table.getModel().getValueAt(4, 0).toString()+":"+Wod_table.getModel().getValueAt(4, 2).toString()
                    +" \n\n\n Thank you \n ECU GYM Staff");
       
           
           // message.setText();
            
       
     
             Transport.send(message);
             JOptionPane.showMessageDialog(null, "Email sent");
             
            
        }catch(MessagingException e)
        {
            throw  new RuntimeException(e);
        }finally{
            try{
                
                pst.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
       String email = Email.getText();
    }//GEN-LAST:event_EmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Workout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Workout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Workout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Workout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Workout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Advance;
    private javax.swing.JRadioButton Arms;
    private javax.swing.JRadioButton Beginner;
    private javax.swing.ButtonGroup Bodypart;
    private javax.swing.JRadioButton Chest;
    private javax.swing.JTextField Email;
    private javax.swing.JRadioButton Endurance;
    private javax.swing.JRadioButton Intermediate;
    private javax.swing.JRadioButton Legs;
    private javax.swing.JRadioButton Muscle_Building;
    private javax.swing.JRadioButton Shoulder;
    private javax.swing.JTable Wod_table;
    private javax.swing.ButtonGroup Workout_Level;
    private javax.swing.ButtonGroup Workout_type;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
